name: Deploy to GHCR
on:
   push:
    branches: [ "main" ] # main 브랜치 올리면 실행 

jobs:
    build-and-push:
        runs-on: ubuntu-lastest  # GitHub 서버에 linux 실행
        permissions:
           contents: read       # 코드 읽기 권한
           packages: write      # GHCR에 이미지 업로드 권한
        steps:
            - name: Code Checkout
              uses: actions/checkout@v4  # 현재 코드를 vm으로 가져옴

            - name: GHCR Login
              # GitHub 내장 토큰 사용해 GHCR 로그인(gitHub secret 생성: GHCR_TOKEN) 
              run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Image Build n Upload
              run: |
                # 1. 저장소 이름을 소문자로 변환해야 에러 방지
                REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                # 2. Dockerfile로 Image 생성 (태그명은 소문자)
                docker build -t ghcr.io/${{ github.repository }}:latest .
                # 3. 빌드된 이미지 GHCR 푸쉬
                docker push ghcr.io/${{ github.repository }}:latest         